<!doctype html>
<html lang="id">
<head>
<meta charset="utf-8">
<style>
@page{size:A4 portrait;margin:5mm}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,sans-serif;color:#10213f}.page{width:100%;page-break-after:always}.page:last-child{page-break-after:auto}.sheet{width:100%;border-collapse:collapse;table-layout:fixed}.slot{width:50%;height:56mm;padding:1mm 2mm;vertical-align:top}.card{position:relative;width:85.6mm;height:54mm;margin:0 auto;overflow:hidden;border:.25mm dashed #94a3b8;background:#fff}.top{height:10.5mm;background:#102a56;color:#fff;border-bottom:1.2mm solid #dc2626}.brand{width:100%;border-collapse:collapse}.mark{width:11mm;padding:1.4mm 0 1mm 2.2mm}.mark-circle{width:7.2mm;height:7.2mm;border-radius:50%;background:#fff;color:#174ea6;text-align:center;font-size:11px;font-weight:900;line-height:7.2mm}.school{padding-top:1.1mm;font-size:9px;font-weight:900;line-height:1.2}.school small{display:block;font-size:5.7px;font-weight:400;letter-spacing:.6px}.badge-cell{width:21mm;padding-right:2mm;text-align:right}.badge{display:inline-block;border-radius:8px;background:#fff;color:#102a56;padding:1mm 2mm;font-size:5.8px;font-weight:900;text-transform:uppercase}.body{width:100%;height:39.5mm;border-collapse:collapse}.photo-cell{width:19mm;padding:2.2mm 1.5mm 1mm 2.2mm;vertical-align:top}.photo{width:15mm;height:18.5mm;border:.35mm solid #cbd5e1;object-fit:cover}.initials{width:15mm;height:18.5mm;background:#dbeafe;color:#174ea6;text-align:center;font-size:16px;font-weight:900;line-height:18.5mm}.info{padding:2mm 1mm 1mm 0;vertical-align:top;overflow:hidden}.name{max-width:43mm;height:5mm;overflow:hidden;font-size:10px;font-weight:900;line-height:5mm;white-space:nowrap;text-overflow:ellipsis}.type{margin-bottom:1.2mm;color:#2563a9;font-size:5.8px;font-weight:900;text-transform:uppercase}.details{width:100%;border-collapse:collapse;font-size:6.2px;line-height:1.25}.details td{padding:.35mm 0;vertical-align:top}.label{width:18mm;color:#64748b}.value{max-width:27mm;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.qr-cell{width:23mm;padding:2.2mm 2mm 1mm 1mm;text-align:center;vertical-align:top}.qr{width:20mm;height:20mm}.scan{margin-top:.4mm;color:#64748b;font-size:5px}.status{margin-top:1.2mm;display:inline-block;border-radius:7px;background:#dcfce7;color:#166534;padding:.7mm 1.6mm;font-size:5.5px;font-weight:900}.status.suspended{background:#fef3c7;color:#92400e}.status.inactive{background:#e2e8f0;color:#475569}.bottom{position:absolute;right:0;bottom:0;left:0;height:3mm;background:#eef4ff;border-top:.7mm solid #dc2626;color:#475569;text-align:center;font-size:4.8px;line-height:2.3mm;letter-spacing:.3px}
</style>
</head>
<body>
@foreach($cards->chunk(10) as $page)
<div class="page"><table class="sheet">
@foreach($page->chunk(2) as $row)
<tr>@foreach($row as $card)
@php($initials = collect(preg_split('/\s+/', trim($card['name'])))->filter()->take(2)->map(fn ($part) => mb_strtoupper(mb_substr($part, 0, 1)))->implode(''))
@php($statusLabel = ['active' => 'Aktif', 'suspended' => 'Ditangguhkan', 'inactive' => 'Tidak aktif'][$card['member_status']] ?? ucfirst((string) $card['member_status']))
<td class="slot"><div class="card"><div class="top"><table class="brand"><tr><td class="mark"><div class="mark-circle">BM</div></td><td class="school">SMK BINA MANDIRI<small>PERPUSTAKAAN SEKOLAH</small></td><td class="badge-cell"><span class="badge">Kartu Anggota</span></td></tr></table></div><table class="body"><tr><td class="photo-cell">@if($card['photo_image'])<img class="photo" src="{{ $card['photo_image'] }}" alt="Foto">@else<div class="initials">{{ $initials ?: 'BM' }}</div>@endif</td><td class="info"><div class="name">{{ $card['name'] }}</div><div class="type">{{ $card['member_type'] === 'student' ? 'Siswa' : 'Staf' }}</div><table class="details"><tr><td class="label">NIS/NIP</td><td class="value">{{ $card['nis_nip'] ?: '-' }}</td></tr><tr><td class="label">No. anggota</td><td class="value">{{ $card['member_number'] ?: '-' }}</td></tr><tr><td class="label">Kelas/Jabatan</td><td class="value">{{ $card['class_name'] ?: '-' }}</td></tr>@if($card['major'])<tr><td class="label">Jurusan</td><td class="value">{{ $card['major'] }}</td></tr>@endif @if($card['academic_year'])<tr><td class="label">Tahun ajaran</td><td class="value">{{ $card['academic_year'] }}</td></tr>@endif</table></td><td class="qr-cell"><img class="qr" src="{{ $card['qr_image'] }}" alt="QR"><div class="scan">Pindai untuk identifikasi</div><span class="status {{ $card['member_status'] }}">{{ $statusLabel }}</span></td></tr></table><div class="bottom">KARTU INI MILIK PERPUSTAKAAN SMK BINA MANDIRI</div></div></td>
@endforeach @if($row->count() === 1)<td class="slot"></td>@endif</tr>
@endforeach
</table></div>
@endforeach
</body>
</html>