import { useCallback, useEffect, useState } from 'react'
import { Feedback, PageHeader } from '../components/ui'
import { api, ApiError } from '../lib/api'

const empty = { years: [], levels: [], majors: [], classes: [] }
const initialForms = { years: { name: '', starts_at: '', ends_at: '' }, levels: { name: '', sort_order: '' }, majors: { code: '', name: '' }, classes: { academic_year_id: '', education_level_id: '', major_id: '', group_name: '' } }
export default function AcademicMasterPage() {
  const [data, setData] = useState(empty); const [forms, setForms] = useState(initialForms); const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [errors, setErrors] = useState({}); const [message, setMessage] = useState('')
  const [editingClass, setEditingClass] = useState(null); const [deleteTarget, setDeleteTarget] = useState(null)
  const load = useCallback(async () => { try { const response = await api('/api/academic'); setData(response.data ?? empty); setError('') } catch (reason) { setError(reason.message) } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  useEffect(() => { if (!deleteTarget) return undefined; const previousOverflow = document.body.style.overflow; const closeOnEscape = (event) => { if (event.key === 'Escape' && !busy) setDeleteTarget(null) }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', closeOnEscape); return () => { document.body.style.overflow = previousOverflow; window.removeEventListener('keydown', closeOnEscape) } }, [busy, deleteTarget])
  const clearFeedback = () => { setError(''); setErrors({}); setMessage('') }
  const change = (type, field, value) => setForms((current) => ({ ...current, [type]: { ...current[type], [field]: value } }))
  const create = async (type, event) => { event.preventDefault(); if (busy) return; setBusy(type); clearFeedback(); try { const payload = Object.fromEntries(Object.entries(forms[type]).filter(([, value]) => value !== '')); await api(`/api/academic/${type}`, { method: 'POST', body: JSON.stringify(payload) }); setForms((current) => ({ ...current, [type]: initialForms[type] })); setMessage('Data master berhasil ditambahkan.'); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Tidak dapat terhubung ke server.'); setErrors(reason instanceof ApiError ? reason.errors : {}) } finally { setBusy('') } }
  const submitClass = async (event) => { event.preventDefault(); if (busy) return; const isEditing = Boolean(editingClass); setBusy(isEditing ? `edit-class-${editingClass.id}` : 'classes'); clearFeedback(); try { const payload = Object.fromEntries(Object.entries(forms.classes).filter(([, value]) => value !== '')); await api(isEditing ? `/api/academic/classes/${editingClass.id}` : '/api/academic/classes', { method: isEditing ? 'PUT' : 'POST', body: JSON.stringify(payload) }); setForms((current) => ({ ...current, classes: initialForms.classes })); setEditingClass(null); setMessage(isEditing ? 'Kelas berhasil diperbarui.' : 'Data master berhasil ditambahkan.'); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Tidak dapat terhubung ke server.'); setErrors(reason instanceof ApiError ? reason.errors : {}) } finally { setBusy('') } }
  const startEdit = (item) => { if (Number(item.assignments_count ?? 0) > 0 || busy) return; clearFeedback(); setEditingClass(item); setForms((current) => ({ ...current, classes: { academic_year_id: String(item.academic_year_id ?? item.academic_year?.id ?? ''), education_level_id: String(item.education_level_id ?? item.education_level?.id ?? ''), major_id: String(item.major_id ?? item.major?.id ?? ''), group_name: item.group_name ?? '' } })); window.setTimeout(() => document.getElementById('class-form')?.scrollIntoView({ behavior: 'smooth', block: 'center' }), 0) }
  const cancelEdit = () => { if (busy) return; setEditingClass(null); setForms((current) => ({ ...current, classes: initialForms.classes })); clearFeedback() }
  const toggle = async (type, item) => { if (busy) return; setBusy(`${type}-${item.id}`); clearFeedback(); try { await api(`/api/academic/${type}/${item.id}/toggle`, { method: 'PATCH' }); setMessage(`${item.is_active ? 'Data dinonaktifkan' : 'Data diaktifkan'} berhasil.`); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Tidak dapat terhubung ke server.'); setErrors(reason instanceof ApiError ? reason.errors : {}) } finally { setBusy('') } }
  const askDelete = (item) => { if (Number(item.assignments_count ?? 0) > 0 || busy) return; clearFeedback(); setDeleteTarget(item) }
  const deleteClass = async () => { if (!deleteTarget || busy || Number(deleteTarget.assignments_count ?? 0) > 0) return; const target = deleteTarget; setBusy(`delete-class-${target.id}`); clearFeedback(); try { await api(`/api/academic/classes/${target.id}`, { method: 'DELETE' }); setDeleteTarget(null); if (editingClass?.id === target.id) { setEditingClass(null); setForms((current) => ({ ...current, classes: initialForms.classes })) } setMessage(`Kelas ${target.display_name} berhasil dihapus.`); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Tidak dapat terhubung ke server.'); setErrors(reason instanceof ApiError ? reason.errors : {}) } finally { setBusy('') } }
  const active = (items) => items.filter((item) => item.is_active)
  return <div className="space-y-6"><PageHeader eyebrow="Master data" title="Struktur akademik" description="Kelola tahun ajaran, tingkatan, jurusan, dan kelas. Seluruh pilihan registrasi siswa berasal dari data aktif di sini." />{error && <Feedback type="error">{error}</Feedback>}{message && <Feedback type="success">{message}</Feedback>}
    <div className="grid gap-5 xl:grid-cols-2"><MasterCard title="Tahun ajaran" count={data.years.length}><form onSubmit={(event) => create('years', event)} className="grid gap-3 sm:grid-cols-3"><Input label="Tahun" placeholder="2026/2027" value={forms.years.name} onChange={(v) => change('years', 'name', v)} error={errors.name} disabled={Boolean(busy)} /><Input label="Mulai" type="date" value={forms.years.starts_at} onChange={(v) => change('years', 'starts_at', v)} disabled={Boolean(busy)} /><Input label="Selesai" type="date" value={forms.years.ends_at} onChange={(v) => change('years', 'ends_at', v)} error={errors.ends_at} disabled={Boolean(busy)} /><Submit busy={busy === 'years'} disabled={Boolean(busy)} /></form><MasterList loading={loading} items={data.years} type="years" busy={busy} toggle={toggle} primary={(item) => item.name} secondary={(item) => dateRange(item)} /></MasterCard>
      <MasterCard title="Tingkatan" count={data.levels.length}><form onSubmit={(event) => create('levels', event)} className="grid gap-3 sm:grid-cols-2"><Input label="Nama tingkat" placeholder="10" value={forms.levels.name} onChange={(v) => change('levels', 'name', v)} error={errors.name} disabled={Boolean(busy)} /><Input label="Urutan" type="number" placeholder="10" value={forms.levels.sort_order} onChange={(v) => change('levels', 'sort_order', v)} error={errors.sort_order} disabled={Boolean(busy)} /><Submit busy={busy === 'levels'} disabled={Boolean(busy)} /></form><MasterList loading={loading} items={data.levels} type="levels" busy={busy} toggle={toggle} primary={(item) => `Kelas ${item.name}`} secondary={(item) => `Urutan ${item.sort_order}`} /></MasterCard>
      <MasterCard title="Jurusan" count={data.majors.length}><form onSubmit={(event) => create('majors', event)} className="grid gap-3 sm:grid-cols-[.55fr_1.45fr]"><Input label="Kode" placeholder="TKJ" value={forms.majors.code} onChange={(v) => change('majors', 'code', v)} error={errors.code} disabled={Boolean(busy)} /><Input label="Nama jurusan" placeholder="Teknik Komputer dan Jaringan" value={forms.majors.name} onChange={(v) => change('majors', 'name', v)} error={errors.name} disabled={Boolean(busy)} /><Submit busy={busy === 'majors'} disabled={Boolean(busy)} /></form><MasterList loading={loading} items={data.majors} type="majors" busy={busy} toggle={toggle} primary={(item) => item.code} secondary={(item) => item.name} /></MasterCard>
      <MasterCard title="Kelas / Rombel" count={data.classes.length}><form id="class-form" onSubmit={submitClass} className="grid gap-3 sm:grid-cols-2"><Select label="Tahun ajaran" value={forms.classes.academic_year_id} onChange={(v) => change('classes', 'academic_year_id', v)} items={editingClass ? data.years : active(data.years)} text={(item) => item.name} error={errors.academic_year_id} disabled={Boolean(busy)} /><Select label="Tingkatan" value={forms.classes.education_level_id} onChange={(v) => change('classes', 'education_level_id', v)} items={editingClass ? data.levels : active(data.levels)} text={(item) => item.name} error={errors.education_level_id} disabled={Boolean(busy)} /><Select label="Jurusan" value={forms.classes.major_id} onChange={(v) => change('classes', 'major_id', v)} items={editingClass ? data.majors : active(data.majors)} text={(item) => `${item.code} — ${item.name}`} error={errors.major_id} disabled={Boolean(busy)} /><Input label="Rombel" placeholder="A" value={forms.classes.group_name} onChange={(v) => change('classes', 'group_name', v)} error={errors.group_name} disabled={Boolean(busy)} /><div className="flex flex-col-reverse gap-2 sm:col-span-2 sm:flex-row sm:justify-end">{editingClass && <button type="button" disabled={Boolean(busy)} onClick={cancelEdit} className="min-h-11 rounded-xl border border-slate-300 px-5 text-sm font-bold text-slate-700 disabled:opacity-50">Batal</button>}<Submit busy={busy === 'classes' || busy.startsWith('edit-class-')} disabled={Boolean(busy)} label={editingClass ? 'Simpan perubahan' : '+ Tambah kelas'} compact /></div></form><ClassList loading={loading} items={data.classes} busy={busy} toggle={toggle} onEdit={startEdit} onDelete={askDelete} /></MasterCard></div>
    {deleteTarget && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/65 p-3 backdrop-blur-sm sm:p-6" role="presentation" onMouseDown={() => { if (!busy) setDeleteTarget(null) }}><div role="dialog" aria-modal="true" aria-labelledby="delete-class-title" aria-describedby="delete-class-description" className="mx-auto my-16 max-w-md overflow-hidden rounded-3xl bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="p-5 sm:p-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-red-50 text-2xl text-red-700" aria-hidden="true">!</span><h2 id="delete-class-title" className="mt-4 text-xl font-black text-navy-950">Hapus kelas?</h2><p id="delete-class-description" className="mt-2 text-sm leading-6 text-slate-600">Kelas <strong>{deleteTarget.display_name}</strong> akan dihapus permanen. Tindakan ini tidak dapat dibatalkan.</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" disabled={Boolean(busy)} onClick={() => setDeleteTarget(null)} className="min-h-11 rounded-xl border border-slate-300 px-5 font-bold text-slate-700 disabled:opacity-50">Batal</button><button type="button" disabled={Boolean(busy)} onClick={deleteClass} className="min-h-11 rounded-xl bg-red-600 px-5 font-bold text-white hover:bg-red-700 disabled:opacity-60">{busy === `delete-class-${deleteTarget.id}` ? 'Menghapus…' : 'Hapus kelas'}</button></div></div></div></div>}
  </div>
}
function MasterCard({ title, count, children }) { return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black text-navy-950">{title}</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">{count} data</span></div>{children}</section> }
function Input({ label, value, onChange, error, disabled, type = 'text', placeholder }) { return <label className="text-sm font-bold text-slate-700">{label}<input required={type !== 'date'} disabled={disabled} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal disabled:bg-slate-100" />{error && <small className="text-red-600">{error[0]}</small>}</label> }
function Select({ label, value, onChange, items, text, error, disabled }) { return <label className="text-sm font-bold text-slate-700">{label}<select required disabled={disabled} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal disabled:bg-slate-100"><option value="">Pilih data</option>{items.map((item) => <option key={item.id} value={item.id}>{text(item)}</option>)}</select>{error && <small className="text-red-600">{error[0]}</small>}</label> }
function Submit({ busy, disabled, label = '+ Tambah data', compact = false }) { return <button disabled={disabled} className={`min-h-11 self-end rounded-xl bg-blue-700 px-4 text-sm font-bold text-white hover:bg-blue-800 disabled:opacity-50 ${compact ? '' : 'sm:col-span-full'}`}>{busy ? 'Menyimpan…' : label}</button> }
function MasterList({ loading, items, type, busy, toggle, primary, secondary }) { if (loading) return <div className="mt-5 h-24 animate-pulse rounded-2xl bg-slate-100" />; if (!items.length) return <p className="mt-5 rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500">Belum ada data.</p>; return <div className="mt-5 max-h-72 space-y-2 overflow-y-auto pr-1">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-3"><div className="min-w-0"><p className="truncate text-sm font-black text-slate-800">{primary(item)}</p><p className="truncate text-xs text-slate-500">{secondary(item) || 'Master akademik'}</p></div><button type="button" disabled={Boolean(busy)} onClick={() => toggle(type, item)} className={`min-h-9 shrink-0 rounded-lg px-3 text-xs font-bold disabled:opacity-50 ${item.is_active ? 'bg-blue-50 text-blue-700' : 'bg-slate-100 text-slate-500'}`}>{busy === `${type}-${item.id}` ? 'Memproses…' : item.is_active ? 'Aktif' : 'Nonaktif'}</button></div>)}</div> }
function ClassList({ loading, items, busy, toggle, onEdit, onDelete }) { if (loading) return <div className="mt-5 h-24 animate-pulse rounded-2xl bg-slate-100" />; if (!items.length) return <p className="mt-5 rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500">Belum ada data.</p>; return <div className="mt-5 max-h-96 space-y-3 overflow-y-auto pr-1">{items.map((item) => { const historyCount = Number(item.assignments_count ?? 0); const used = historyCount > 0; return <article key={item.id} className="rounded-2xl border border-slate-200 p-3 sm:p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="font-black text-slate-800">{item.display_name}</p><p className="mt-0.5 text-xs text-slate-500">{item.academic_year?.name || 'Tahun ajaran belum tersedia'}</p><p className="mt-2 text-xs font-bold text-slate-600">Histori siswa: {historyCount}</p>{used && <p className="mt-1 text-xs leading-5 text-amber-700">Kelas terpakai tidak dapat diedit atau dihapus; hanya dapat dinonaktifkan.</p>}</div><button type="button" disabled={Boolean(busy)} onClick={() => toggle('classes', item)} className={`min-h-9 shrink-0 rounded-lg px-3 text-xs font-bold disabled:opacity-50 ${item.is_active ? 'bg-blue-50 text-blue-700' : 'bg-slate-100 text-slate-500'}`}>{busy === `classes-${item.id}` ? 'Memproses…' : item.is_active ? 'Aktif' : 'Nonaktif'}</button></div><div className="mt-3 flex flex-col gap-2 border-t border-slate-100 pt-3 min-[400px]:flex-row"><button type="button" disabled={Boolean(busy) || used} title={used ? 'Kelas dengan histori siswa tidak dapat diedit.' : 'Edit kelas'} onClick={() => onEdit(item)} className="min-h-10 flex-1 rounded-xl border border-slate-300 px-4 text-sm font-bold text-blue-700 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400">Edit</button><button type="button" disabled={Boolean(busy) || used} title={used ? 'Kelas dengan histori siswa tidak dapat dihapus.' : 'Hapus kelas'} onClick={() => onDelete(item)} className="min-h-10 flex-1 rounded-xl border border-red-200 px-4 text-sm font-bold text-red-600 disabled:cursor-not-allowed disabled:border-slate-200 disabled:bg-slate-100 disabled:text-slate-400">Hapus</button></div></article> })}</div> }
function dateRange(item) { const format = (value) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(value)) : null; return [format(item.starts_at), format(item.ends_at)].filter(Boolean).join(' — ') || 'Tanggal belum diatur' }
