import { useEffect, useState } from 'react'
import { api, ApiError } from '../lib/api'

const empty = { years: [], levels: [], majors: [], classes: [] }
const initialForms = { years: { name: '', starts_at: '', ends_at: '' }, levels: { name: '', sort_order: '' }, majors: { code: '', name: '' }, classes: { academic_year_id: '', education_level_id: '', major_id: '', group_name: '' } }
export default function AcademicMasterPage() {
  const [data, setData] = useState(empty); const [forms, setForms] = useState(initialForms); const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [errors, setErrors] = useState({}); const [message, setMessage] = useState('')
  const load = async () => { try { const response = await api('/api/academic'); setData(response.data); setError('') } catch (reason) { setError(reason.message) } finally { setLoading(false) } }
  useEffect(() => { api('/api/academic').then((response) => setData(response.data)).catch((reason) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const change = (type, field, value) => setForms((current) => ({ ...current, [type]: { ...current[type], [field]: value } }))
  const create = async (type, event) => { event.preventDefault(); setBusy(type); setError(''); setErrors({}); setMessage(''); try { const payload = Object.fromEntries(Object.entries(forms[type]).filter(([, value]) => value !== '')); await api(`/api/academic/${type}`, { method: 'POST', body: JSON.stringify(payload) }); setForms((current) => ({ ...current, [type]: initialForms[type] })); setMessage('Data master berhasil ditambahkan.'); await load() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Tidak dapat terhubung ke server.'); setErrors(reason instanceof ApiError ? reason.errors : {}) } finally { setBusy('') } }
  const toggle = async (type, item) => { setBusy(`${type}-${item.id}`); setError(''); try { await api(`/api/academic/${type}/${item.id}/toggle`, { method: 'PATCH' }); setMessage(`${item.is_active ? 'Data dinonaktifkan' : 'Data diaktifkan'} berhasil.`); await load() } catch (reason) { setError(reason.message) } finally { setBusy('') } }
  const active = (items) => items.filter((item) => item.is_active)
  return <><header><p className="text-sm font-black tracking-widest text-blue-700">MASTER DATA</p><h1 className="mt-1 text-3xl font-black text-navy-950">Struktur akademik</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Kelola tahun ajaran, tingkatan, jurusan, dan kelas. Seluruh pilihan registrasi siswa berasal dari data aktif di sini.</p></header>{error && <div role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{message && <div className="mt-5 rounded-xl bg-blue-50 p-4 text-sm text-blue-800">{message}</div>}
    <div className="mt-6 grid gap-5 xl:grid-cols-2"><MasterCard title="Tahun ajaran" count={data.years.length}><form onSubmit={(event) => create('years', event)} className="grid gap-3 sm:grid-cols-3"><Input label="Tahun" placeholder="2026/2027" value={forms.years.name} onChange={(v) => change('years', 'name', v)} error={errors.name} /><Input label="Mulai" type="date" value={forms.years.starts_at} onChange={(v) => change('years', 'starts_at', v)} /><Input label="Selesai" type="date" value={forms.years.ends_at} onChange={(v) => change('years', 'ends_at', v)} error={errors.ends_at} /><Submit busy={busy === 'years'} /></form><MasterList loading={loading} items={data.years} type="years" busy={busy} toggle={toggle} primary={(item) => item.name} secondary={(item) => dateRange(item)} /></MasterCard>
      <MasterCard title="Tingkatan" count={data.levels.length}><form onSubmit={(event) => create('levels', event)} className="grid gap-3 sm:grid-cols-2"><Input label="Nama tingkat" placeholder="10" value={forms.levels.name} onChange={(v) => change('levels', 'name', v)} error={errors.name} /><Input label="Urutan" type="number" placeholder="10" value={forms.levels.sort_order} onChange={(v) => change('levels', 'sort_order', v)} error={errors.sort_order} /><Submit busy={busy === 'levels'} /></form><MasterList loading={loading} items={data.levels} type="levels" busy={busy} toggle={toggle} primary={(item) => `Kelas ${item.name}`} secondary={(item) => `Urutan ${item.sort_order}`} /></MasterCard>
      <MasterCard title="Jurusan" count={data.majors.length}><form onSubmit={(event) => create('majors', event)} className="grid gap-3 sm:grid-cols-[.55fr_1.45fr]"><Input label="Kode" placeholder="TKJ" value={forms.majors.code} onChange={(v) => change('majors', 'code', v)} error={errors.code} /><Input label="Nama jurusan" placeholder="Teknik Komputer dan Jaringan" value={forms.majors.name} onChange={(v) => change('majors', 'name', v)} error={errors.name} /><Submit busy={busy === 'majors'} /></form><MasterList loading={loading} items={data.majors} type="majors" busy={busy} toggle={toggle} primary={(item) => item.code} secondary={(item) => item.name} /></MasterCard>
      <MasterCard title="Kelas / Rombel" count={data.classes.length}><form onSubmit={(event) => create('classes', event)} className="grid gap-3 sm:grid-cols-2"><Select label="Tahun ajaran" value={forms.classes.academic_year_id} onChange={(v) => change('classes', 'academic_year_id', v)} items={active(data.years)} text={(item) => item.name} error={errors.academic_year_id} /><Select label="Tingkatan" value={forms.classes.education_level_id} onChange={(v) => change('classes', 'education_level_id', v)} items={active(data.levels)} text={(item) => item.name} error={errors.education_level_id} /><Select label="Jurusan" value={forms.classes.major_id} onChange={(v) => change('classes', 'major_id', v)} items={active(data.majors)} text={(item) => `${item.code} — ${item.name}`} error={errors.major_id} /><Input label="Rombel" placeholder="A" value={forms.classes.group_name} onChange={(v) => change('classes', 'group_name', v)} error={errors.group_name} /><Submit busy={busy === 'classes'} /></form><MasterList loading={loading} items={data.classes} type="classes" busy={busy} toggle={toggle} primary={(item) => item.display_name} secondary={(item) => item.academic_year?.name} /></MasterCard></div></>
}
function MasterCard({ title, count, children }) { return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black text-navy-950">{title}</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-700">{count} data</span></div>{children}</section> }
function Input({ label, value, onChange, error, type = 'text', placeholder }) { return <label className="text-sm font-bold text-slate-700">{label}<input required={type !== 'date'} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" />{error && <small className="text-red-600">{error[0]}</small>}</label> }
function Select({ label, value, onChange, items, text, error }) { return <label className="text-sm font-bold text-slate-700">{label}<select required value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 font-normal"><option value="">Pilih data</option>{items.map((item) => <option key={item.id} value={item.id}>{text(item)}</option>)}</select>{error && <small className="text-red-600">{error[0]}</small>}</label> }
function Submit({ busy }) { return <button disabled={busy} className="min-h-11 self-end rounded-xl bg-blue-700 px-4 text-sm font-bold text-white hover:bg-blue-800 disabled:opacity-50 sm:col-span-full">{busy ? 'Menyimpan…' : '+ Tambah data'}</button> }
function MasterList({ loading, items, type, busy, toggle, primary, secondary }) { if (loading) return <div className="mt-5 h-24 animate-pulse rounded-2xl bg-slate-100" />; if (!items.length) return <p className="mt-5 rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500">Belum ada data.</p>; return <div className="mt-5 max-h-72 space-y-2 overflow-y-auto pr-1">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-3"><div className="min-w-0"><p className="truncate text-sm font-black text-slate-800">{primary(item)}</p><p className="truncate text-xs text-slate-500">{secondary(item) || 'Master akademik'}</p></div><button type="button" disabled={busy === `${type}-${item.id}`} onClick={() => toggle(type, item)} className={`min-h-9 shrink-0 rounded-lg px-3 text-xs font-bold ${item.is_active ? 'bg-blue-50 text-blue-700' : 'bg-slate-100 text-slate-500'}`}>{item.is_active ? 'Aktif' : 'Nonaktif'}</button></div>)}</div> }
function dateRange(item) { const format = (value) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(value)) : null; return [format(item.starts_at), format(item.ends_at)].filter(Boolean).join(' — ') || 'Tanggal belum diatur' }
