import { useEffect, useState } from 'react'
import { EmptyState, Feedback, LoadingRows, PageHeader, Panel, formatDate } from '../components/ui'
import { api } from '../lib/api'

export default function AuditPage() {
  const [logs, setLogs] = useState([]); const [action, setAction] = useState(''); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ current: 1, last: 1, total: 0 })
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState(null)
  useEffect(() => { let cancelled = false; const timer = setTimeout(() => { setLoading(true); setError(''); const params = new URLSearchParams({ action, page: String(page) }); api(`/api/activity-logs?${params}`).then((response) => { if (cancelled) return; setLogs(response.data ?? []); setPagination({ current: response.current_page ?? 1, last: response.last_page ?? 1, total: response.total ?? response.data?.length ?? 0 }) }).catch((reason) => { if (!cancelled) setError(reason.message) }).finally(() => { if (!cancelled) setLoading(false) }) }, 250); return () => { cancelled = true; clearTimeout(timer) } }, [action, page])
  const search = (event) => { setAction(event.target.value); setPage(1) }
  return <div className="space-y-6"><PageHeader eyebrow="Keamanan" title="Audit log" description="Jejak aktivitas penting sistem yang bersifat permanen dan tidak dapat diedit." />
    {error && <Feedback type="error">{error}</Feedback>}<Panel title="Aktivitas sistem" description={`${pagination.total} catatan audit`} action={<label><span className="sr-only">Cari jenis aksi</span><input type="search" value={action} onChange={search} placeholder="Cari aksi, contoh: loan" className="min-h-11 w-full rounded-xl border border-slate-300 px-4 text-sm sm:w-72" /></label>}>
      {loading ? <LoadingRows count={6} /> : logs.length ? <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><th className="pb-4">Waktu</th><th className="pb-4">Pengguna</th><th className="pb-4">Aksi</th><th className="pb-4">Deskripsi</th><th className="pb-4">Alamat IP</th><th className="pb-4 text-right">Detail</th></tr></thead><tbody className="divide-y divide-slate-100">{logs.map((log) => <tr key={log.id}><td className="py-4 pr-4 whitespace-nowrap">{formatDate(log.created_at, true)}</td><td className="py-4 pr-4 font-semibold">{log.user?.name ?? 'Sistem'}</td><td className="py-4 pr-4"><code className="rounded-lg bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{log.action}</code></td><td className="max-w-xs truncate py-4 pr-4 text-slate-600">{log.description ?? summarize(log.changes)}</td><td className="py-4 pr-4 font-mono text-xs text-slate-500">{log.ip_address ?? '-'}</td><td className="py-4 text-right"><button onClick={() => setSelected(log)} className="min-h-9 rounded-lg border border-slate-300 px-3 text-xs font-bold text-slate-700 hover:border-blue-300 hover:text-blue-700">Lihat</button></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{logs.map((log) => <article key={log.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><code className="rounded-lg bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{log.action}</code><span className="text-[10px] text-slate-400">{formatDate(log.created_at, true)}</span></div><p className="mt-3 text-sm font-bold text-slate-800">{log.user?.name ?? 'Sistem'}</p><p className="mt-1 line-clamp-2 text-xs text-slate-500">{log.description ?? summarize(log.changes)}</p><button onClick={() => setSelected(log)} className="mt-3 min-h-9 w-full rounded-lg border border-slate-300 text-xs font-bold">Lihat detail</button></article>)}</div></> : <EmptyState icon="◎" title="Log tidak ditemukan" description="Ubah kata pencarian atau belum ada aktivitas yang tercatat." />}
      {!loading && pagination.last > 1 && <nav className="mt-5 flex items-center justify-between border-t border-slate-100 pt-5"><button disabled={pagination.current <= 1} onClick={() => setPage((value) => value - 1)} className="min-h-10 rounded-xl border border-slate-300 px-4 text-sm font-bold disabled:opacity-40">Sebelumnya</button><span className="text-xs text-slate-500">{pagination.current} / {pagination.last}</span><button disabled={pagination.current >= pagination.last} onClick={() => setPage((value) => value + 1)} className="min-h-10 rounded-xl border border-slate-300 px-4 text-sm font-bold disabled:opacity-40">Berikutnya</button></nav>}
    </Panel>{selected && <DetailModal log={selected} onClose={() => setSelected(null)} />}</div>
}
function summarize(value) { if (!value) return 'Tidak ada detail perubahan'; const text = typeof value === 'string' ? value : JSON.stringify(value); return text.length > 120 ? `${text.slice(0, 120)}…` : text }
function DetailModal({ log, onClose }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/65 p-4 backdrop-blur-sm" onMouseDown={onClose}><div role="dialog" aria-modal="true" className="mx-auto my-12 max-w-2xl rounded-3xl bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between border-b border-slate-100 p-6"><div><p className="text-xs font-black uppercase tracking-wider text-blue-700">Detail audit</p><h2 className="mt-2 text-xl font-black text-navy-950">{log.action}</h2><p className="mt-1 text-sm text-slate-500">{formatDate(log.created_at, true)}</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-xl">×</button></div><dl className="grid gap-4 p-6 sm:grid-cols-2"><Info label="Pengguna" value={log.user?.name ?? 'Sistem'} /><Info label="Alamat IP" value={log.ip_address ?? '-'} /><Info label="Deskripsi" value={log.description ?? '-'} wide /><div className="sm:col-span-2"><dt className="text-xs font-bold uppercase text-slate-400">Data perubahan</dt><dd><pre className="mt-2 max-h-80 overflow-auto rounded-2xl bg-slate-950 p-4 text-xs leading-6 text-slate-200">{JSON.stringify(log.changes ?? {}, null, 2)}</pre></dd></div></dl></div></div> }
function Info({ label, value, wide }) { return <div className={wide ? 'sm:col-span-2' : ''}><dt className="text-xs font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value}</dd></div> }
