import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'
import { useAuth } from '../store/auth'

const currency = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 })
const fullDate = new Intl.DateTimeFormat('id-ID', { dateStyle: 'full' })
const shortDate = new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })
const pageLoadedAt = Date.now()
async function requestDashboard() {
  const [dashboard, active] = await Promise.allSettled([api('/api/dashboard'), api('/api/loans/active')])
  return { stats: dashboard.status === 'fulfilled' ? dashboard.value.data : {}, loans: active.status === 'fulfilled' ? active.value.data ?? [] : [], failed: [dashboard, active].filter((item) => item.status === 'rejected').length }
}

export default function DashboardPage() {
  const { user, permissions } = useAuth(); const [stats, setStats] = useState({}); const [loans, setLoans] = useState([])
  const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(0)
  const admin = permissions.includes('loans.view-all'); const canCirculate = permissions.some((permission) => ['circulation.borrow', 'circulation.return'].includes(permission))
  useEffect(() => { let mounted = true; requestDashboard().then((result) => { if (!mounted) return; setStats(result.stats); setLoans(result.loans); setFailed(result.failed); setLoading(false) }); return () => { mounted = false } }, [])
  const retry = async () => { setLoading(true); const result = await requestDashboard(); setStats(result.stats); setLoans(result.loans); setFailed(result.failed); setLoading(false) }
  const cards = admin ? [
    { label: 'Total anggota', value: stats.users, helper: 'Anggota terdaftar', icon: 'users' },
    { label: 'Judul buku', value: stats.books, helper: `${stats.copies ?? 0} eksemplar fisik`, icon: 'books' },
    { label: 'Tersedia', value: stats.available_copies, helper: `Dari ${stats.copies ?? 0} eksemplar`, icon: 'available', tone: 'blue' },
    { label: 'Dipinjam', value: stats.active_loans, helper: 'Transaksi aktif', icon: 'loans' },
    { label: 'Terlambat', value: stats.overdue_loans, helper: Number(stats.overdue_loans) ? 'Perlu ditindaklanjuti' : 'Semua tepat waktu', icon: 'clock', tone: Number(stats.overdue_loans) ? 'amber' : 'neutral' },
    { label: 'Denda berjalan', value: currency.format(Number(stats.unpaid_fines ?? 0)), helper: 'Belum diselesaikan', icon: 'fine', tone: Number(stats.unpaid_fines) ? 'red' : 'neutral', compact: true },
  ] : [
    { label: 'Sedang dipinjam', value: stats.active_loans, helper: 'Buku aktif', icon: 'loans', tone: 'blue' },
    { label: 'Terlambat', value: stats.overdue_loans, helper: Number(stats.overdue_loans) ? 'Segera kembalikan' : 'Tidak ada keterlambatan', icon: 'clock', tone: Number(stats.overdue_loans) ? 'amber' : 'neutral' },
    { label: 'Riwayat', value: stats.history_count, helper: 'Total peminjaman', icon: 'history' },
    { label: 'Denda', value: currency.format(Number(stats.unpaid_fines ?? 0)), helper: 'Tagihan berjalan', icon: 'fine', tone: Number(stats.unpaid_fines) ? 'red' : 'neutral', compact: true },
  ]
  const nearestLoan = [...loans].sort((a, b) => new Date(a.due_at) - new Date(b.due_at))[0]
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-navy-950 via-navy-900 to-blue-900 px-6 py-7 text-white shadow-xl shadow-slate-900/10 sm:px-8 sm:py-8"><div className="absolute -right-16 -top-24 h-72 w-72 rounded-full bg-blue-500/20 blur-2xl" /><div className="absolute bottom-0 right-[28%] h-32 w-32 rounded-full bg-red-500/10 blur-2xl" /><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-200">{fullDate.format(new Date())}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Selamat datang, {user.name.split(' ')[0]}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100 sm:text-base">{admin ? 'Ringkasan operasional perpustakaan dan hal penting yang perlu Anda tangani hari ini.' : 'Pantau pinjaman, batas pengembalian, dan koleksi terbaru untuk Anda.'}</p></div>{canCirculate && <Link to="/scan" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-black text-navy-950 shadow-lg hover:bg-blue-50"><DashboardIcon name="scan" />{permissions.includes('circulation.borrow') ? 'Mulai transaksi' : 'Proses pengembalian'}<span aria-hidden="true">→</span></Link>}</div></section>

    {failed > 0 && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><span>Sebagian data dashboard belum berhasil dimuat.</span><button onClick={retry} className="min-h-9 rounded-lg bg-amber-900 px-4 text-xs font-bold text-white">Muat ulang</button></div>}
    <section className={`grid gap-4 sm:grid-cols-2 ${admin ? 'lg:grid-cols-3 2xl:grid-cols-6' : 'lg:grid-cols-4'}`} aria-label="Ringkasan statistik">{loading ? Array.from({ length: admin ? 6 : 4 }, (_, index) => <StatSkeleton key={index} />) : cards.map((card) => <StatCard key={card.label} {...card} />)}</section>

    {admin ? <AdminDashboard stats={stats} loans={loans} loading={loading} permissions={permissions} /> : <MemberDashboard stats={stats} loans={loans} nearestLoan={nearestLoan} loading={loading} />}
  </div>
}

function AdminDashboard({ stats, loans, loading, permissions }) { return <div className="grid gap-6 xl:grid-cols-12"><Panel className="xl:col-span-8" title="Pinjaman aktif terbaru" subtitle="Transaksi yang masih berjalan" action={<Link to="/loans" className="text-xs font-black text-blue-700 hover:text-blue-900">Lihat semua →</Link>}>{loading ? <ListSkeleton /> : <LoanList loans={loans} showMember />}</Panel><Panel className="xl:col-span-4" title="Perlu perhatian" subtitle="Prioritas operasional hari ini"><div className="space-y-3"><Attention tone={Number(stats.overdue_loans) ? 'red' : 'green'} label="Peminjaman terlambat" value={`${stats.overdue_loans ?? 0} transaksi`} to="/loans" /><Attention tone={Number(stats.unpaid_fines) ? 'amber' : 'green'} label="Denda belum selesai" value={currency.format(Number(stats.unpaid_fines ?? 0))} to="/fines" /><Attention tone="blue" label="Ketersediaan koleksi" value={`${stats.available_copies ?? 0} dari ${stats.copies ?? 0} eksemplar`} to="/inventory" visible={permissions.includes('catalog.create')} /></div></Panel><Panel className="xl:col-span-8" title="Aktivitas peminjaman" subtitle="Pergerakan enam bulan terakhir"><ActivityChart items={stats.monthly_activity ?? []} loading={loading} /></Panel><Panel className="xl:col-span-4" title="Buku paling populer" subtitle="Berdasarkan frekuensi peminjaman">{loading ? <ListSkeleton rows={4} /> : <PopularBooks books={stats.popular_books ?? []} />}</Panel></div> }
function MemberDashboard({ stats, loans, nearestLoan, loading }) { return <div className="grid gap-6 xl:grid-cols-12">{nearestLoan && <section className="overflow-hidden rounded-3xl border border-blue-100 bg-blue-50 p-5 xl:col-span-12 sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-xs font-black uppercase tracking-wider text-blue-700">Pengembalian terdekat</p><h3 className="mt-2 text-xl font-black text-navy-950">{nearestLoan.book_copy?.book?.title ?? 'Buku perpustakaan'}</h3><p className="mt-1 text-sm text-slate-600">Nomor inventaris {nearestLoan.book_copy?.inventory_code ?? '-'}</p></div><DueBadge dueAt={nearestLoan.due_at} large /></div></section>}<Panel className="xl:col-span-7" title="Pinjaman saya" subtitle="Buku yang sedang Anda pinjam" action={<Link to="/loans" className="text-xs font-black text-blue-700">Lihat riwayat →</Link>}>{loading ? <ListSkeleton /> : <LoanList loans={loans} />}</Panel><Panel className="xl:col-span-5" title="Rekomendasi terbaru" subtitle="Koleksi yang tersedia untuk dipinjam">{loading ? <ListSkeleton rows={4} /> : <RecommendationList books={stats.recommendations ?? []} />}</Panel></div> }
function StatCard({ label, value, helper, icon, tone = 'neutral', compact }) { const styles = { neutral: 'border-slate-200 bg-white text-slate-700', blue: 'border-blue-100 bg-blue-50 text-blue-800', amber: 'border-amber-200 bg-amber-50 text-amber-900', red: 'border-red-200 bg-red-50 text-red-800' }; const icons = { neutral: 'bg-slate-100 text-slate-600', blue: 'bg-blue-100 text-blue-700', amber: 'bg-amber-100 text-amber-700', red: 'bg-red-100 text-red-700' }; return <article className={`rounded-2xl border p-5 shadow-sm shadow-slate-900/[.02] ${styles[tone]}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold text-slate-500">{label}</p><p className={`mt-2 truncate font-black tracking-tight text-navy-950 ${compact ? 'text-xl' : 'text-2xl'}`}>{value ?? 0}</p></div><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${icons[tone]}`}><DashboardIcon name={icon} /></span></div><p className="mt-3 truncate text-[11px] text-slate-500">{helper}</p></article> }
function Panel({ title, subtitle, action, className = '', children }) { return <section className={`rounded-3xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-900/[.025] sm:p-6 ${className}`}><header className="mb-5 flex items-start justify-between gap-4"><div><h3 className="text-base font-black text-navy-950 sm:text-lg">{title}</h3><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div>{action}</header>{children}</section> }
function LoanList({ loans, showMember = false }) { if (!loans.length) return <EmptyState title="Belum ada pinjaman aktif" description="Transaksi peminjaman akan tampil di bagian ini." />; return <div className="divide-y divide-slate-100">{loans.slice(0, 6).map((loan) => <div key={loan.id} className="flex flex-col gap-3 py-4 first:pt-0 last:pb-0 sm:flex-row sm:items-center"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><DashboardIcon name="books" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{loan.book_copy?.book?.title ?? 'Judul tidak tersedia'}</p><p className="mt-1 truncate text-xs text-slate-500">{showMember ? `${loan.user?.name ?? 'Anggota'} • ${loan.user?.nis_nip ?? '-'}` : `Inventaris ${loan.book_copy?.inventory_code ?? '-'}`}</p></div><DueBadge dueAt={loan.due_at} /></div>)}</div> }
function DueBadge({ dueAt, large = false }) { const date = new Date(dueAt); const days = Math.ceil((date.getTime() - pageLoadedAt) / 86400000); const overdue = days < 0; const soon = days >= 0 && days <= 2; const label = overdue ? `Terlambat ${Math.abs(days)} hari` : days === 0 ? 'Jatuh tempo hari ini' : `${days} hari lagi`; return <div className={`shrink-0 rounded-xl px-3 py-2 ${overdue ? 'bg-red-50 text-red-700' : soon ? 'bg-amber-50 text-amber-700' : 'bg-slate-50 text-slate-600'} ${large ? 'min-w-48 text-center' : 'sm:text-right'}`}><p className="text-[10px] font-black uppercase tracking-wide">{label}</p><p className="mt-0.5 text-xs font-bold">{shortDate.format(date)}</p></div> }
function Attention({ label, value, to, tone, visible = true }) { if (!visible) return null; const styles = { red: 'bg-red-50 text-red-700', amber: 'bg-amber-50 text-amber-700', green: 'bg-emerald-50 text-emerald-700', blue: 'bg-blue-50 text-blue-700' }; return <Link to={to} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-3.5 hover:border-blue-200 hover:shadow-sm"><span className={`h-9 w-1 rounded-full ${styles[tone]}`} /><span className="min-w-0 flex-1"><b className="block truncate text-xs text-slate-700">{label}</b><small className="mt-1 block truncate text-slate-500">{value}</small></span><span className="text-slate-300">→</span></Link> }
function ActivityChart({ items, loading }) { if (loading) return <div className="h-48 animate-pulse rounded-2xl bg-slate-100" />; if (!items.length) return <EmptyState title="Belum ada aktivitas" description="Grafik muncul setelah transaksi pertama." />; const max = Math.max(1, ...items.map((item) => Number(item.loans))); return <div className="pt-3"><div className="flex h-48 items-end gap-3 sm:gap-5">{items.map((month) => <div key={month.label} className="flex h-full flex-1 flex-col items-center justify-end gap-2" aria-label={`${month.label}: ${month.loans} peminjaman`}><span className="text-xs font-black text-slate-700">{month.loans}</span><div className="w-full max-w-14 rounded-t-xl bg-gradient-to-t from-blue-700 to-blue-400" style={{ height: `${Math.max(8, (Number(month.loans) / max) * 140)}px` }} /><span className="text-center text-[10px] font-semibold text-slate-400">{month.label}</span></div>)}</div></div> }
function PopularBooks({ books }) { if (!books.length) return <EmptyState title="Belum ada statistik" description="Buku populer akan dihitung dari transaksi." />; return <ol className="space-y-2.5">{books.map((book, index) => <li key={book.title} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg text-xs font-black ${index === 0 ? 'bg-blue-700 text-white' : 'bg-white text-slate-500'}`}>{index + 1}</span><span className="min-w-0 flex-1 truncate text-xs font-bold text-slate-700">{book.title}</span><small className="shrink-0 text-[10px] font-bold text-slate-400">{book.loans}×</small></li>)}</ol> }
function RecommendationList({ books }) { if (!books.length) return <EmptyState title="Belum ada rekomendasi" description="Koleksi baru akan ditampilkan di sini." />; return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{books.map((book) => <Link key={book.id} to="/catalog" className="group rounded-2xl border border-slate-100 bg-slate-50 p-4 hover:border-blue-200 hover:bg-blue-50"><p className="line-clamp-2 text-sm font-bold text-slate-800 group-hover:text-blue-800">{book.title}</p><p className="mt-2 truncate text-xs text-slate-500">{book.author || 'Penulis tidak diketahui'}</p><span className="mt-3 inline-block text-[11px] font-black text-blue-700">Lihat katalog →</span></Link>)}</div> }
function EmptyState({ title, description }) { return <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50 px-5 py-9 text-center"><p className="text-sm font-bold text-slate-700">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div> }
function StatSkeleton() { return <div className="h-36 animate-pulse rounded-2xl border border-slate-200 bg-white p-5"><div className="h-3 w-20 rounded bg-slate-100" /><div className="mt-4 h-8 w-16 rounded bg-slate-100" /><div className="mt-4 h-3 w-28 rounded bg-slate-100" /></div> }
function ListSkeleton({ rows = 5 }) { return <div className="space-y-3">{Array.from({ length: rows }, (_, index) => <div key={index} className="h-14 animate-pulse rounded-xl bg-slate-100" />)}</div> }
function DashboardIcon({ name }) { const paths = { scan: 'M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4M8 12h8', users: 'M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm8-1a4 4 0 0 1 0 7', books: 'M4 5a2 2 0 0 1 2-2h5v16H6a2 2 0 0 0-2 2V5Zm16 0a2 2 0 0 0-2-2h-5v16h5a2 2 0 0 1 2 2V5Z', available: 'm5 12 4 4L19 6', loans: 'M7 7h11l-3-3m3 3-3 3M17 17H6l3 3m-3-3 3-3', clock: 'M12 22a10 10 0 1 0-10-10 10 10 0 0 0 10 10Zm0-15v5l3 2', fine: 'M12 2v20m5-16H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H7', history: 'M3 12a9 9 0 1 0 3-6.7L3 8m0-5v5h5m4-1v5l3 2' }; return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] ?? paths.books} /></svg> }
