import { useCallback, useEffect, useState } from 'react'
import { EmptyState, Feedback, LoadingRows, PageHeader, Panel, formatCurrency } from '../components/ui'
import { api } from '../lib/api'
import { useAuth } from '../store/auth'

export default function FinesPage() {
  const permissions = useAuth((state) => state.permissions); const [fines, setFines] = useState([]); const [loading, setLoading] = useState(true)
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [action, setAction] = useState(null); const [form, setForm] = useState({ amount: '', reason: '' }); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setError(''); try { const response = await api('/api/fines'); setFines(response.data ?? []) } catch (reason) { setError(reason.message) } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [load])
  useEffect(() => { if (!action) return undefined; const previous = document.body.style.overflow; const close = (event) => { if (event.key === 'Escape' && !busy) setAction(null) }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close); return () => { document.body.style.overflow = previous; window.removeEventListener('keydown', close) } }, [action, busy])
  const remaining = (fine) => Math.max(0, Number(fine.amount) - Number(fine.paid_amount))
  const open = (type, fine) => { setAction({ type, fine }); setForm({ amount: type === 'pay' ? String(remaining(fine)) : '', reason: '' }); setError('') }
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { if (action.type === 'pay') await api(`/api/fines/${action.fine.id}/payments`, { method: 'POST', body: JSON.stringify({ amount: Number(form.amount), method: 'cash' }) }); else await api(`/api/fines/${action.fine.id}/waive`, { method: 'POST', body: JSON.stringify({ reason: form.reason.trim() }) }); setMessage(action.type === 'pay' ? 'Pembayaran denda berhasil dicatat.' : 'Denda berhasil dibebaskan.'); setAction(null); await load() } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  const outstanding = fines.reduce((total, fine) => total + remaining(fine), 0); const active = fines.filter((fine) => !['paid', 'waived'].includes(fine.status)).length
  return <div className="space-y-6"><PageHeader eyebrow="Keuangan" title="Denda anggota" description="Pantau saldo denda dan catat penyelesaian transaksi secara aman." />
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Total tagihan" value={formatCurrency(outstanding)} tone={outstanding ? 'red' : 'blue'} /><Metric label="Belum selesai" value={`${active} denda`} tone={active ? 'amber' : 'blue'} /><Metric label="Total data" value={`${fines.length} transaksi`} /></div>
    {message && <Feedback type="success">{message}</Feedback>}{error && !action && <Feedback type="error">{error}</Feedback>}
    <Panel title="Daftar denda" description="Saldo dihitung dari nominal denda dikurangi pembayaran"><div className="space-y-3">{loading ? <LoadingRows count={5} /> : fines.length ? fines.map((fine) => <FineCard key={fine.id} fine={fine} remaining={remaining(fine)} canPay={permissions.includes('fines.pay')} canWaive={permissions.includes('fines.waive')} onAction={open} />) : <EmptyState icon="Rp" title="Tidak ada denda" description="Tagihan anggota akan tampil pada halaman ini." />}</div></Panel>
    {action && <ActionModal action={action} form={form} setForm={setForm} busy={busy} error={error} remaining={remaining(action.fine)} onClose={() => !busy && setAction(null)} onSubmit={submit} />}
  </div>
}
function FineCard({ fine, remaining, canPay, canWaive, onAction }) { const resolved = ['paid', 'waived'].includes(fine.status); const status = ({ unpaid: 'Belum dibayar', partial: 'Dibayar sebagian', paid: 'Lunas', waived: 'Dibebaskan' })[fine.status] ?? fine.status; return <article className="rounded-2xl border border-slate-200 p-4 sm:p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-slate-900">{fine.loan?.book_copy?.book?.title ?? 'Denda perpustakaan'}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${resolved ? 'bg-emerald-50 text-emerald-700' : fine.status === 'partial' ? 'bg-amber-50 text-amber-700' : 'bg-red-50 text-red-700'}`}>{status}</span></div><p className="mt-1 text-sm text-slate-500">{fine.loan?.user?.name ?? 'Anggota'} • {fine.loan?.user?.nis_nip ?? '-'}</p></div><div className="sm:text-right"><p className="text-xs font-bold text-slate-400">SISA TAGIHAN</p><p className={`mt-1 text-xl font-black ${remaining ? 'text-red-700' : 'text-emerald-700'}`}>{formatCurrency(remaining)}</p><p className="text-xs text-slate-400">dari {formatCurrency(fine.amount)}</p></div></div>{canPay && !resolved && <div className="mt-4 flex flex-col gap-2 border-t border-slate-100 pt-4 sm:flex-row sm:justify-end"><button onClick={() => onAction('pay', fine)} className="min-h-10 rounded-xl bg-blue-700 px-4 text-sm font-bold text-white hover:bg-blue-800">Catat pembayaran</button>{canWaive && <button onClick={() => onAction('waive', fine)} className="min-h-10 rounded-xl border border-amber-300 px-4 text-sm font-bold text-amber-700 hover:bg-amber-50">Bebaskan denda</button>}</div>}</article> }
function Metric({ label, value, tone = 'neutral' }) { const style = tone === 'red' ? 'border-red-200 bg-red-50 text-red-800' : tone === 'amber' ? 'border-amber-200 bg-amber-50 text-amber-800' : tone === 'blue' ? 'border-blue-200 bg-blue-50 text-blue-800' : 'border-slate-200 bg-white text-navy-950'; return <div className={`rounded-2xl border p-5 ${style}`}><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div> }
function ActionModal({ action, form, setForm, busy, error, remaining, onClose, onSubmit }) { const payment = action.type === 'pay'; return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/65 p-4 backdrop-blur-sm" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby="fine-action-title" className="mx-auto my-12 max-w-lg rounded-3xl bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="border-b border-slate-100 p-6"><p className="text-xs font-black uppercase tracking-wider text-blue-700">Penyelesaian denda</p><h2 id="fine-action-title" className="mt-2 text-2xl font-black text-navy-950">{payment ? 'Catat pembayaran' : 'Bebaskan denda'}</h2><p className="mt-1 text-sm text-slate-500">{action.fine.loan?.user?.name} • sisa {formatCurrency(remaining)}</p></div><form onSubmit={onSubmit} className="space-y-4 p-6">{error && <Feedback type="error">{error}</Feedback>}{payment ? <label className="block text-sm font-bold text-slate-700">Nominal pembayaran<input required type="number" min="1" max={remaining} value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4" /><small className="mt-1 block text-slate-500">Metode pembayaran: tunai</small></label> : <label className="block text-sm font-bold text-slate-700">Alasan pembebasan<textarea required minLength="5" rows="4" value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="Jelaskan alasan pembebasan untuk audit…" /></label>}<div className="flex flex-col-reverse gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:justify-end"><button type="button" disabled={busy} onClick={onClose} className="min-h-11 rounded-xl border border-slate-300 px-5 font-bold text-slate-700">Batal</button><button disabled={busy} className={`min-h-11 rounded-xl px-5 font-bold text-white ${payment ? 'bg-blue-700' : 'bg-amber-600'}`}>{busy ? 'Memproses…' : payment ? 'Simpan pembayaran' : 'Konfirmasi pembebasan'}</button></div></form></div></div> }
