import { useEffect, useState } from 'react'
import { EmptyState, Feedback, LoadingRows, PageHeader, Panel, Tabs, formatDate } from '../components/ui'
import { api } from '../lib/api'

const pageLoadedAt = Date.now()
const tabItems = [{ value: 'active', label: 'Sedang dipinjam' }, { value: 'history', label: 'Riwayat' }]
export default function LoansPage() {
  const [tab, setTab] = useState('active'); const [page, setPage] = useState(1); const [loans, setLoans] = useState([])
  const [pagination, setPagination] = useState({ current: 1, last: 1, total: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let cancelled = false; setLoading(true); setError(''); api(`/api/loans/${tab}?page=${page}`).then((response) => { if (cancelled) return; setLoans(response.data ?? []); setPagination({ current: response.current_page ?? 1, last: response.last_page ?? 1, total: response.total ?? 0 }) }).catch((reason) => { if (!cancelled) setError(reason.message) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [page, tab])
  const changeTab = (value) => { setTab(value); setPage(1) }
  const overdueCount = loans.filter((loan) => loanState(loan) === 'overdue').length
  return <div className="space-y-6"><PageHeader eyebrow="Sirkulasi" title="Pinjaman" description="Pantau buku yang sedang dipinjam, batas pengembalian, dan seluruh riwayat transaksi." />
    <div className="flex flex-wrap items-center justify-between gap-4"><Tabs items={tabItems} value={tab} onChange={changeTab} /><div className="flex gap-2"><Summary label="Total data" value={pagination.total} /><Summary label="Terlambat" value={overdueCount} danger={overdueCount > 0} /></div></div>
    {error && <Feedback type="error">{error}</Feedback>}
    <Panel title={tab === 'active' ? 'Pinjaman aktif' : 'Riwayat pengembalian'} description={`${pagination.total} transaksi ditemukan`}>
      {loading ? <LoadingRows count={5} /> : loans.length ? <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><th className="pb-4">Buku</th><th className="pb-4">Anggota</th><th className="pb-4">Kode inventaris</th><th className="pb-4">Tenggat</th><th className="pb-4 text-right">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{loans.map((loan) => <LoanRow key={loan.id} loan={loan} />)}</tbody></table></div><div className="space-y-3 md:hidden">{loans.map((loan) => <LoanCard key={loan.id} loan={loan} />)}</div></> : <EmptyState icon="↔" title="Tidak ada data pinjaman" description={tab === 'active' ? 'Belum ada buku yang sedang dipinjam.' : 'Riwayat transaksi masih kosong.'} />}
      {!loading && pagination.last > 1 && <Pagination pagination={pagination} setPage={setPage} />}
    </Panel>
  </div>
}
function loanState(loan) { if (loan.returned_at || loan.status === 'returned') return 'returned'; return loan.status === 'overdue' || (loan.due_at && new Date(loan.due_at).getTime() < pageLoadedAt) ? 'overdue' : 'active' }
function badge(state) { return ({ active: ['Aktif', 'bg-blue-50 text-blue-700'], overdue: ['Terlambat', 'bg-red-50 text-red-700'], returned: ['Dikembalikan', 'bg-emerald-50 text-emerald-700'] })[state] ?? [state, 'bg-slate-100 text-slate-600'] }
function LoanRow({ loan }) { const [label, style] = badge(loanState(loan)); return <tr><td className="py-4 pr-4"><p className="font-bold text-slate-900">{loan.book_copy?.book?.title ?? '-'}</p></td><td className="py-4 pr-4"><p className="font-semibold text-slate-700">{loan.user?.name ?? 'Akun saya'}</p><p className="text-xs text-slate-500">{loan.user?.nis_nip ?? '-'}</p></td><td className="py-4 pr-4 font-mono text-xs font-bold text-slate-600">{loan.book_copy?.inventory_code ?? '-'}</td><td className="py-4 pr-4"><p className="font-semibold text-slate-700">{formatDate(loan.due_at)}</p>{loan.returned_at && <p className="text-xs text-slate-500">Kembali {formatDate(loan.returned_at)}</p>}</td><td className="py-4 text-right"><span className={`rounded-full px-3 py-1 text-xs font-bold ${style}`}>{label}</span></td></tr> }
function LoanCard({ loan }) { const [label, style] = badge(loanState(loan)); return <article className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-black text-slate-900">{loan.book_copy?.book?.title ?? '-'}</h3><p className="mt-1 truncate text-xs text-slate-500">{loan.user?.name ?? 'Akun saya'} • {loan.book_copy?.inventory_code ?? '-'}</p></div><span className={`shrink-0 rounded-full px-3 py-1 text-xs font-bold ${style}`}>{label}</span></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-xs"><p><span className="text-slate-500">Dipinjam</span><br /><b>{formatDate(loan.borrowed_at)}</b></p><p><span className="text-slate-500">Jatuh tempo</span><br /><b>{formatDate(loan.due_at)}</b></p></div></article> }
function Summary({ label, value, danger }) { return <div className={`rounded-xl border px-3 py-2 text-right ${danger ? 'border-red-200 bg-red-50' : 'border-slate-200 bg-white'}`}><p className="text-[10px] font-bold uppercase text-slate-400">{label}</p><p className={`text-sm font-black ${danger ? 'text-red-700' : 'text-navy-950'}`}>{value}</p></div> }
function Pagination({ pagination, setPage }) { return <nav className="mt-5 flex items-center justify-between gap-3 border-t border-slate-100 pt-5"><button disabled={pagination.current <= 1} onClick={() => setPage((value) => value - 1)} className="min-h-10 rounded-xl border border-slate-300 px-4 text-sm font-bold disabled:opacity-40">Sebelumnya</button><span className="text-xs font-semibold text-slate-500">Halaman {pagination.current} dari {pagination.last}</span><button disabled={pagination.current >= pagination.last} onClick={() => setPage((value) => value + 1)} className="min-h-10 rounded-xl border border-slate-300 px-4 text-sm font-bold disabled:opacity-40">Berikutnya</button></nav> }
