import { QRCodeSVG } from 'qrcode.react'
import { useEffect, useRef, useState } from 'react'
import { api, ApiError } from '../lib/api'
import { useAuth } from '../store/auth'

const API_URL = import.meta.env.VITE_API_URL ?? ''

export default function ProfilePage() {
  const authUser = useAuth((state) => state.user); const qrRef = useRef(null)
  const [card, setCard] = useState(null); const [form, setForm] = useState({ name: authUser.name, phone: authUser.phone ?? '', class_or_position: authUser.class_or_position ?? '' })
  const [photo, setPhoto] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [errors, setErrors] = useState({})
  const isStudent = authUser.member_type === 'student'
  const loadCard = async () => { try { const response = await api('/api/profile/card'); setCard(response.data); setError('') } catch (reason) { setError(reason.message) } finally { setLoading(false) } }
  useEffect(() => { api('/api/profile/card').then((response) => setCard(response.data)).catch((reason) => setError(reason.message)).finally(() => setLoading(false)) }, [])
  const save = async (event) => { event.preventDefault(); setSaving(true); setMessage(''); setError(''); setErrors({}); const body = new FormData(); Object.entries(form).forEach(([key, value]) => { if (!(isStudent && key === 'class_or_position')) body.append(key, value) }); if (photo) body.append('photo', photo); try { const response = await api('/api/profile', { method: 'POST', headers: { 'X-HTTP-Method-Override': 'PUT' }, body }); useAuth.setState((state) => ({ user: { ...state.user, ...response.data } })); setMessage('Profil berhasil diperbarui.'); await loadCard() } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Profil tidak dapat disimpan.'); setErrors(reason instanceof ApiError ? reason.errors : {}) } finally { setSaving(false) } }
  const saveQr = () => { const svg = qrRef.current?.querySelector('svg'); if (!svg || !card) return; const blob = new Blob([new XMLSerializer().serializeToString(svg)], { type: 'image/svg+xml' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `qr-${card.member_number ?? card.nis_nip ?? card.id}.svg`; anchor.click(); URL.revokeObjectURL(url) }
  const photoUrl = card?.photo_path ? `${API_URL}/storage/${card.photo_path}` : null
  return <><header><p className="text-sm font-black tracking-widest text-blue-700">AKUN</p><h1 className="mt-1 text-3xl font-black text-navy-950">Profil & kartu anggota</h1><p className="mt-2 text-sm text-slate-500">Perbarui informasi kontak dan simpan kartu perpustakaan digital.</p></header>
    <div className="mt-6 grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><form onSubmit={save} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black text-navy-950">Informasi profil</h2>{message && <p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Field label="Nama lengkap" value={form.name} onChange={(value) => setForm({ ...form, name: value })} error={errors.name} /><Field label="Nomor telepon" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} error={errors.phone} />{isStudent ? <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-bold text-blue-700">KELAS AKTIF</p><p className="mt-1 font-black text-navy-950">{card?.class_name ?? 'Belum ditetapkan'}</p><p className="mt-1 text-xs text-slate-500">Perubahan kelas dilakukan admin melalui data akademik.</p></div> : <Field label="Jabatan" value={form.class_or_position} onChange={(value) => setForm({ ...form, class_or_position: value })} error={errors.class_or_position} />}<label className="mt-4 block text-sm font-bold text-slate-700">Foto profil<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setPhoto(event.target.files?.[0] ?? null)} className="mt-2 block w-full rounded-xl border border-slate-300 p-2 font-normal" />{errors.photo && <small className="text-red-600">{errors.photo[0]}</small>}</label><button disabled={saving} className="mt-6 min-h-12 w-full rounded-xl bg-blue-700 font-bold text-white hover:bg-blue-800 disabled:opacity-50">{saving ? 'Menyimpan…' : 'Simpan profil'}</button></form>
      <section id="member-card" className="relative overflow-hidden rounded-3xl bg-navy-950 p-6 text-white shadow-xl sm:p-8"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-blue-600/25" /><div className="absolute bottom-0 left-0 h-2 w-full bg-red-600" />{loading ? <div className="h-96 animate-pulse rounded-2xl bg-white/10" /> : card ? <div className="relative"><div className="flex items-center justify-between gap-4 border-b border-white/15 pb-5"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-red-600 font-black">BM</span><div><p className="font-black">SMK BINA MANDIRI</p><p className="text-xs font-bold tracking-widest text-blue-200">KARTU PERPUSTAKAAN</p></div></div><Status value={card.member_status} /></div><div className="mt-6 grid items-center gap-6 sm:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-4">{photoUrl ? <img src={photoUrl} alt={`Foto ${card.name}`} className="h-24 w-20 rounded-xl border-2 border-white/30 object-cover" /> : <div className="grid h-24 w-20 place-items-center rounded-xl bg-white/10 text-3xl font-black">{card.name.charAt(0)}</div>}<div><p className="text-xs font-bold text-blue-200">NAMA ANGGOTA</p><h2 className="mt-1 text-2xl font-black">{card.name}</h2><p className="mt-1 text-sm text-blue-100">NIS: {card.nis_nip ?? '-'}</p></div></div><dl className="mt-6 grid grid-cols-2 gap-x-5 gap-y-4"><Info label="Nomor anggota" value={card.member_number ?? '-'} /><Info label="Kelas" value={card.class_name ?? '-'} /><Info label="Jurusan" value={card.major ?? '-'} /><Info label="Tahun ajaran" value={card.academic_year ?? '-'} /></dl></div><div ref={qrRef} className="mx-auto rounded-2xl bg-white p-4"><QRCodeSVG value={card.qr_token} size={170} level="M" /></div></div><div className="print-hidden mt-7 grid gap-3 sm:grid-cols-2"><button type="button" onClick={saveQr} className="min-h-11 rounded-xl bg-white/10 px-4 font-bold hover:bg-white/20">Unduh QR</button><button type="button" onClick={() => window.print()} className="min-h-11 rounded-xl bg-blue-600 px-4 font-bold hover:bg-blue-500">Cetak / Simpan PDF</button></div></div> : <p className="relative rounded-xl bg-red-500/15 p-4 text-sm">Kartu anggota belum tersedia.</p>}</section></div></>
}
function Field({ label, value, onChange, error }) { return <label className="mt-4 block text-sm font-bold text-slate-700">{label}<input required value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal" />{error && <small className="text-red-600">{error[0]}</small>}</label> }
function Info({ label, value }) { return <div><dt className="text-[10px] font-bold uppercase tracking-wider text-blue-200">{label}</dt><dd className="mt-1 text-sm font-black">{value}</dd></div> }
function Status({ value }) { const active = value === 'active'; return <span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${active ? 'bg-blue-500/25 text-blue-100' : 'bg-red-500/25 text-red-100'}`}>{active ? 'Aktif' : value ?? 'Tidak aktif'}</span> }
