import { useState } from 'react'
import { EmptyState, Feedback, PageHeader, Panel } from '../components/ui'
import { download } from '../lib/api'

const reportTypes = [{ value: 'circulation', label: 'Sirkulasi', description: 'Peminjaman dan pengembalian buku' }, { value: 'fines', label: 'Denda', description: 'Tagihan dan pembayaran anggota' }, { value: 'inventory', label: 'Inventaris', description: 'Koleksi dan status eksemplar' }]
export default function ReportsPage() {
  const [form, setForm] = useState({ type: 'circulation', format: 'xlsx', from: '', to: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState('')
  const submit = async (event) => { event.preventDefault(); setError(''); setSuccess(''); if (form.from && form.to && form.from > form.to) { setError('Tanggal awal tidak boleh melewati tanggal akhir.'); return } const query = new URLSearchParams(Object.fromEntries(Object.entries(form).filter(([, value]) => value))); setBusy(true); try { await download(`/api/reports/export?${query}`); setSuccess('Laporan berhasil dibuat dan unduhan telah dimulai.') } catch (reason) { setError(reason.message) } finally { setBusy(false) } }
  const selected = reportTypes.find((item) => item.value === form.type)
  return <div className="space-y-6"><PageHeader eyebrow="Analitik" title="Pusat laporan" description="Buat laporan operasional yang siap disimpan, dicetak, atau dianalisis lebih lanjut." />{error && <Feedback type="error">{error}</Feedback>}{success && <Feedback type="success">{success}</Feedback>}
    <div className="grid gap-6 xl:grid-cols-[1fr_1.5fr]"><section className="space-y-3">{reportTypes.map((item) => <button type="button" key={item.value} onClick={() => setForm({ ...form, type: item.value })} className={`w-full rounded-2xl border p-5 text-left transition ${form.type === item.value ? 'border-blue-300 bg-blue-50 shadow-sm' : 'border-slate-200 bg-white hover:border-blue-200'}`}><div className="flex items-center justify-between"><span className="font-black text-navy-950">{item.label}</span><span className={`h-4 w-4 rounded-full border-4 ${form.type === item.value ? 'border-blue-600' : 'border-slate-300'}`} /></div><p className="mt-2 text-sm text-slate-500">{item.description}</p></button>)}</section>
      <Panel title={`Laporan ${selected?.label}`} description={selected?.description}><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Dari tanggal" type="date" value={form.from} onChange={(value) => setForm({ ...form, from: value })} /><Field label="Sampai tanggal" type="date" value={form.to} onChange={(value) => setForm({ ...form, to: value })} /></div><label className="block text-sm font-bold text-slate-700">Format file<select value={form.format} onChange={(event) => setForm({ ...form, format: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4"><option value="xlsx">Excel (.xlsx)</option><option value="pdf">Dokumen PDF (.pdf)</option><option value="csv">Data CSV (.csv)</option></select></label><div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><p className="font-bold text-slate-800">Ringkasan ekspor</p><p className="mt-2">Jenis: {selected?.label}</p><p>Periode: {form.from || 'Semua tanggal'} — {form.to || 'Sekarang'}</p><p>Format: {form.format.toUpperCase()}</p></div><button disabled={busy} className="min-h-12 w-full rounded-xl bg-blue-700 px-5 font-bold text-white hover:bg-blue-800 disabled:opacity-50">{busy ? 'Membuat laporan…' : 'Unduh laporan'}</button></form></Panel>
    </div><EmptyState icon="i" title="Tips laporan" description="Gunakan rentang tanggal yang lebih sempit agar laporan operasional lebih mudah dianalisis." /></div>
}
function Field({ label, value, onChange, type }) { return <label className="text-sm font-bold text-slate-700">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4" /></label> }
